
package cn.demo.jax.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayHiServiceImplService", targetNamespace = "http://sayhi.service.jax.demo.cn/", wsdlLocation = "http://localhost:8080/project-demo/service/sayHi?wsdl")
public class SayHiServiceImplService
    extends Service
{

    private final static URL SAYHISERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYHISERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SAYHISERVICEIMPLSERVICE_QNAME = new QName("http://sayhi.service.jax.demo.cn/", "SayHiServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/project-demo/service/sayHi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYHISERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SAYHISERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SayHiServiceImplService() {
        super(__getWsdlLocation(), SAYHISERVICEIMPLSERVICE_QNAME);
    }

    public SayHiServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYHISERVICEIMPLSERVICE_QNAME, features);
    }

    public SayHiServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SAYHISERVICEIMPLSERVICE_QNAME);
    }

    public SayHiServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYHISERVICEIMPLSERVICE_QNAME, features);
    }

    public SayHiServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayHiServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServiceImplPort")
    public SayHiService getSayHiServiceImplPort() {
        return super.getPort(new QName("http://sayhi.service.jax.demo.cn/", "SayHiServiceImplPort"), SayHiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServiceImplPort")
    public SayHiService getSayHiServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sayhi.service.jax.demo.cn/", "SayHiServiceImplPort"), SayHiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYHISERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SAYHISERVICEIMPLSERVICE_EXCEPTION;
        }
        return SAYHISERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
